### ISSUE TITLE
Framework Agreement | Missing permission to request credential 

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/portal-iam#136]
### Current Behavior

![image](https://github.com/eclipse-tractusx/portal-iam/assets/46191613/80e173f7-9314-4c40-a327-6304f79ecbd0)

Submission of framework credential fails

### Expected Behavior

Submission of framework credential is successful

### Additional information

The composite roles CX Admin, Company Admin, IT Admin and Business Admin miss the request_ssicredential role from Client `Cl24-CX-SSI-CredentialIssuer`

Detected in version 3.0.0

**Comment by evegufy** [comment]
Missing roles added on int, dev and rc.dev
TODO: update of template instances and documentation

**Comment by thomas-t7** [comment]
I was able to apply for my use case framework agreement. Thanks for the bug fix
<img width="437" alt="image" src="https://github.com/eclipse-tractusx/portal-iam/assets/166804645/c7d00d01-a71c-4633-b78c-a592ee0d8bb6">
