### ISSUE TITLE
New Role for DIM-Middle-Layer Client

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/portal-iam#139]
To support the deletion of a technical user of the dim application a new role is needed for the DIM-Middle-Layer Client.

The new role is `delete_technical_user`.

The role needs to be only created on int, dev and rc environment. We don't need to include it in the release.

**Comment by Phil91** [comment]
@evegufy as discussed, here the new issue

**Comment by evegufy** [comment]
@Phil91 I created the role on INT and assigned it to the technical user.
On dev and rc.dev I created the following from scratch:
- new client for issuer component needed `DIM-Middle-Layer`
  - setup_wallet
  - view_status_list
  - delete_technical_user
- technical user `sa-dim-middle-layer-01` needed which has permission to access `DIM-Middle-Layer` with all its roles
