### ISSUE TITLE
CX Admin is missing role 'upload_certificates'

### ISSUE THREAD

**Issue by typecastcloud** [eclipse-tractusx/portal-iam#142]
### Current Behavior
CX Admin does not have
- 'Cl2-CX-Portal'
   - 'upload_certificates'

### Expected Behavior
CX Admin has **all** Cl2-CX-Portal roles (please correct me if this is intended and close issue)

### Steps To Reproduce
Create user with only CX Admin role.

**Comment by evegufy** [comment]
Hi @typecastcloud according R&R concept this appears to be correct:
![image](https://github.com/eclipse-tractusx/portal-iam/assets/46191613/a170bdd1-ab5d-45ec-98a4-753998a9fa89)
https://github.com/eclipse-tractusx/portal-iam/blob/v3.0.0/docs/technical%20documentation/06.%20Roles%20%26%20Rights%20Concept.md

**Comment by typecastcloud** [comment]
> Hi @typecastcloud according R&R concept this appears to be correct

Seems like our expectation for CX Admin is wrong here. Not very intuitive to have this one exception.

What is the reason? Otherwise you can close the issue.

**Comment by typecastcloud** [comment]
Intended behavior
