### ISSUE TITLE
BPDM: Missing Technical User for Component Communication

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/portal-iam#146]
Currently the initial configuration of the IAM is missing a technical user for the BPDM services to realize the golden record process. 

### Context 

BPDM services communicate with each other over authenticated users to realize the golden record process. So in order to deploy a golden record process, a technical user with the necessary permissions needs to available.

The services expect a technical user with at least these permissions:

Cl7-CX-BPDM

-   read_partner
-   write_partner
-   read_partner_member
-   read_metadata
-   write_metadata
-   read_changelog
-   read_changelog_member

Cl16-CX-BPDMGate

- read_input_partner
- write_input_partner
- read_output_partner
- read_input_changelog
- read_output_changelog
- read_sharing_state
- write_sharing_state
- read_stats

### Suggestion for name and description:

Name: sa-cl7-cx-7
Description: Technical user for BPDM services to communicate between each other to realize the golden record process.

**Comment by evegufy** [comment]
@nicoprow I added the service account with the following permissions (in your list there was missing write_output_partner for Cl16-CX-BPDMGate):
![image](https://github.com/eclipse-tractusx/portal-iam/assets/46191613/e08a71dc-8059-4191-8992-9d553ddc0dee)

TODO:
- add to template instance
- add to portal seeding (to be visible in user adminsitration)

**Comment by jjeroch** [comment]
@evegufy & @nicoprow I wonder if its really a good description of the user.
I suggest to use anything more specific such as: 
`Description: Technical user for PortalGate to establish a secure connection with the Business Partner Data Management (BPDM) Pool. Functional Details: Company Address publishing from Gate to Pool and back.`

**Comment by nicoprow** [comment]
> @evegufy & @nicoprow I wonder if its really a good description of the user. I suggest to use anything more specific such as: `Description: Technical user for PortalGate to establish a secure connection with the Business Partner Data Management (BPDM) Pool. Functional Details: Company Address publishing from Gate to Pool and back.`

This technical user is currently used by more than just the Portal Gate. It is meant to be used by the BPDM services to communicate with and establish the golden record process. The User is used by the Portal Gate, Pool and Cleaning Service Dummy at the moment. Sure, we can add for which services specifically this user is created.
