### ISSUE TITLE
sig#805 - Align portal-iam documentation structure with updated TRG 1

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-iam#187]
### Description
To enhance the consistency and ease of understanding of our products for the open community, TRG 1 was updated.
Make sure to comply with the updated structure:

```
repository
└─── docs/
    └─── architecture/
    └─── admin/
    └─── user/
    └─── api/
    └─── README.md
```

Please TRG 1.05-1.08 for more information:
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-05 
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-06
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-07
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-08

### Acceptance Criteria

- [ ] Adjust the repo related documentation based on trg 1.05 - gather all architecture documentations into `docs/architecture`
- [ ] Adjust the repo related documentation based on trg 1.06 - gather admin related docu into `docs/admin`
- [ ] Adjust the repo related documentation based on trg 1.07 - gather end-user related documentation into `doc/user`
- [ ] Adjust the repo related documentation based on trg 1.08 - Clarify the setup with Evelyn ;) 
- [ ] Adjust the `docs/README.md` regarding your changes 
- [ ] Ensure that all documentation is in English

**Comment by shahmargi12** [comment]
Hi @evegufy 

I’m currently working on organizing the documentation according to the updated TRG structure (TRG 1.05 - 1.08), and I noticed that we have some images stored in the static/ folder.

Could you please clarify the best approach for these images? Specifically:

1. Should the images be classified based on their context (e.g., architecture, admin, user, or API) and moved to their respective /docs/ subfolders?
2. Or, would you prefer that they remain in static/ and simply be referenced from there in the relevant .md files?

I want to ensure the documentation remains as clear and organized as possible, so any guidance you can provide would be greatly appreciated!

**Comment by MaximilianHauer** [comment]
ill assigned the issue to you that not any one else is starting to work on it and in the end we have two contributions for the same issue. 
if you cant assign issues yourself reference someone who can to add you their :)

**Comment by shahmargi12** [comment]
> ill assigned the issue to you that not any one else is starting to work on it and in the end we have two contributions for the same issue. if you cant assign issues yourself reference someone who can to add you their :)
> 
> i would prefer "Or, would you prefer that they remain in static/ and simply be referenced from there in the relevant .md files? " as it is clear where to find the pics but we should ensure that we do the same regarding this in every repo .

Thank you for assigning the issue to me. I understand the concern about duplicate contributions, and I'll ensure that I keep track of it. 
Thanks for the clarification! I’ll keep the images in the static/ folder and reference them in the .md files.
