### ISSUE TITLE
Keycloak Image 24.03. Release

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-iam#47]
## Summary
Keycloak Image finalization for release 24.03.
Additional changes found as part of the e2e test are documented in this ticket and need to get applied before the release 24.03. is closed

### Details

- username mapper for identity providers have been removed from the seeded idps on generic and consortia instances
- attribute `bpn` got updated to `BPNL00000003CRHK` for user `cx-operator.656e8a94-188b-4a3e-9eec-b45d8efd8347` for consortia (generic was already in place)
- add role `view_company_data` of client `Cl16-CX-BPDMGate`to `security-company.555b0b81-6ead-4d3d-8d5d-41c07bb8cfbc` user for consortia 
- add Policy Hub client with view client role and assign to default role
- adjust the seeding configuration for the `Client ID` mapper
  -  change user.session.note value from `clientId` to `client_id`
  -  change claim.name value from `clientId` to `client_id`
- assign to the role `Offer Management` under client technical_user_management the following two permissions of the `Cl2-CX-Portal` client: `view_tech_user_management`; `app_management`
- assign the permission `configure_partner_registration` to the composite role `Registration External` inside the client `technical_user_management`
- add role `view_managed_idp` to `CX Admin`

add role `view_managed_idp` to `Company Admin` & `IT Admin` --> informative because already in place

### Linked Tickets
https://github.com/eclipse-tractusx/portal-iam/issues/46

**Comment by evegufy** [comment]
@evegufy it makes sense to approach this issues in the next sprint, once e2e testing is over
