### ISSUE TITLE
TRG 5.04 CPU / MEM resource requests and limits and are properly set

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/portal-iam#54]
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-04

https://github.com/eclipse-tractusx/portal-iam/blob/df4fef5a89c76662f74d53df472af14b8cc1eb03/charts/centralidp/values.yaml#L166-L173

Is there is a reason why not using ressource requests/limits

**Comment by evegufy** [comment]
@FaGru3n thanks for the hint, I'll set the requests

**Comment by evegufy** [comment]
@FaGru3n requests are implemented, could you please check in main?
regarding setting limits in the default values.yaml: I'll look into the change for the release.
