### ISSUE TITLE
TRG 2.03 repository structure - consultation/charts?

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/portal-iam#55]
There is a Chart directory located in the docs folder with a (maybe) copy of the IAM chart.
Also, there is [portal-iam-helm-chart.md](https://github.com/eclipse-tractusx/portal-iam/blob/main/docs/consultation/portal-iam-helm-chart.md) containing a link, that seems like it should point to that chart. But it is pointing to a non-existing directory

Text: The chart is implemented [here](https://github.com/eclipse-tractusx/portal-iam/blob/main/docs/charts/portal-iam/README.md).

**Comment by evegufy** [comment]
thanks for the hint, I corrected the dead link https://github.com/eclipse-tractusx/portal-iam
